services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: system15
      POSTGRES_DB: whatsapp_bot
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles: ["simple", "proxy"]

  app:
    build: .
    restart: unless-stopped
    env_file:
      - ./.env # apunta a .env.docker.dev o .env.docker.prod según el caso
    environment:
      # Valores por si faltan en .env
      WEB_PORT: "3000"
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
      - ./baileys_auth:/app/baileys_auth
    ports:
      - "3000:3000"
    profiles: ["simple"]

  # Producción con proxy HTTPS
  app_proxy:
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      WEB_PORT: "3000"
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
      - ./baileys_auth:/app/baileys_auth
    networks:
      - webnet
    profiles: ["proxy"]

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      - app_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Monta tus certificados (ajusta rutas/nombres)
      - ./certs/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./certs/privkey.pem:/etc/ssl/private/privkey.pem:ro
    networks:
      - webnet
    profiles: ["proxy"]

volumes:
  db_data:

networks:
  webnet:
    driver: bridge
